### PR TITLE
Use Remote Dust Limit for both outputs

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by canndrew** [comment]
LGTM. Nice catch.

**Comment by knocte** [comment]
The git commit only has a title and only tells the **what**. Can you please add the **why** too?

**Comment by aarani** [comment]
@knocte Commit description added.

**Comment by knocte** [comment]
Sorry but I don't understand the description. The best way to describe this is: what's the bad consequence that happens if this PR is not merged?

**Pull request merged**
